// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWRu2VFqUPTNBl19mtc7E8PrkQjjcqH3g',
    appId: '1:1059896746324:web:72f1a8e36c85361014e8c1',
    messagingSenderId: '1059896746324',
    projectId: 'crudapp-d3032',
    authDomain: 'crudapp-d3032.firebaseapp.com',
    storageBucket: 'crudapp-d3032.appspot.com',
    measurementId: 'G-9DPKBWNTDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGAu6hnrKkoja5IDYNRYYBmtVofZEAMfA',
    appId: '1:1059896746324:android:ba4a54a5de03912c14e8c1',
    messagingSenderId: '1059896746324',
    projectId: 'crudapp-d3032',
    storageBucket: 'crudapp-d3032.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW_67RXiA2kOEhMeaHuWKGDPGwHyPoMO8',
    appId: '1:1059896746324:ios:ba4ac3b686c6046514e8c1',
    messagingSenderId: '1059896746324',
    projectId: 'crudapp-d3032',
    storageBucket: 'crudapp-d3032.appspot.com',
    iosBundleId: 'com.example.firstFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW_67RXiA2kOEhMeaHuWKGDPGwHyPoMO8',
    appId: '1:1059896746324:ios:ba4ac3b686c6046514e8c1',
    messagingSenderId: '1059896746324',
    projectId: 'crudapp-d3032',
    storageBucket: 'crudapp-d3032.appspot.com',
    iosBundleId: 'com.example.firstFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWRu2VFqUPTNBl19mtc7E8PrkQjjcqH3g',
    appId: '1:1059896746324:web:8a43dc37246e4e4d14e8c1',
    messagingSenderId: '1059896746324',
    projectId: 'crudapp-d3032',
    authDomain: 'crudapp-d3032.firebaseapp.com',
    storageBucket: 'crudapp-d3032.appspot.com',
    measurementId: 'G-0RTPPQVTS2',
  );
}
